name: waste_management
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.4.1
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.3

  # State Management
  provider: ^6.0.5
  get: ^4.6.6

  # Networking
  http: ^1.2.2
  connectivity_plus: ^6.0.5

  # Location
  geolocator: ^13.0.1

  # Utilities
  intl: ^0.17.0
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  flutter_rating_bar: ^4.0.1
  flutter_rating_stars: ^1.1.0

  # Local Packages
  user_repository:
    path: packages/user_repository

  products_repository:
    path: packages/products_repository

  transaction_repository:
    path: packages/transaction_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
